package entidades;
// Generated 19/10/2015 06:30:40 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Curso generated by hbm2java
 */
@Entity
@Table(name="curso"
    ,catalog="bd_prueba"
)
public class Curso  implements java.io.Serializable {


     private Integer idCurso;
     private String nomCurso;
     private Set<DetalleCurso> detalleCursos = new HashSet<DetalleCurso>(0);

    public Curso() {
    }

    public Curso(String nomCurso, Set<DetalleCurso> detalleCursos) {
       this.nomCurso = nomCurso;
       this.detalleCursos = detalleCursos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idCurso", unique=true, nullable=false)
    public Integer getIdCurso() {
        return this.idCurso;
    }
    
    public void setIdCurso(Integer idCurso) {
        this.idCurso = idCurso;
    }

    
    @Column(name="nom_curso", length=45)
    public String getNomCurso() {
        return this.nomCurso;
    }
    
    public void setNomCurso(String nomCurso) {
        this.nomCurso = nomCurso;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="curso")
    public Set<DetalleCurso> getDetalleCursos() {
        return this.detalleCursos;
    }
    
    public void setDetalleCursos(Set<DetalleCurso> detalleCursos) {
        this.detalleCursos = detalleCursos;
    }




}


