package entidades;
// Generated 19/10/2015 06:30:40 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DetalleCurso generated by hbm2java
 */
@Entity
@Table(name="detalle_curso"
    ,catalog="bd_prueba"
)
public class DetalleCurso  implements java.io.Serializable {


     private Integer idDetalleCurso;
     private Alumno alumno;
     private Curso curso;
     private Integer nota1;
     private Integer nota2;
     private Integer nota3;
     private Double promedio;

    public DetalleCurso() {
    }

	
    public DetalleCurso(Alumno alumno, Curso curso) {
        this.alumno = alumno;
        this.curso = curso;
    }
    public DetalleCurso(Alumno alumno, Curso curso, Integer nota1, Integer nota2, Integer nota3, Double promedio) {
       this.alumno = alumno;
       this.curso = curso;
       this.nota1 = nota1;
       this.nota2 = nota2;
       this.nota3 = nota3;
       this.promedio = promedio;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idDetalle_Curso", unique=true, nullable=false)
    public Integer getIdDetalleCurso() {
        return this.idDetalleCurso;
    }
    
    public void setIdDetalleCurso(Integer idDetalleCurso) {
        this.idDetalleCurso = idDetalleCurso;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Alumno_idAlumno", nullable=false)
    public Alumno getAlumno() {
        return this.alumno;
    }
    
    public void setAlumno(Alumno alumno) {
        this.alumno = alumno;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Curso_idCurso", nullable=false)
    public Curso getCurso() {
        return this.curso;
    }
    
    public void setCurso(Curso curso) {
        this.curso = curso;
    }

    
    @Column(name="nota1")
    public Integer getNota1() {
        return this.nota1;
    }
    
    public void setNota1(Integer nota1) {
        this.nota1 = nota1;
    }

    
    @Column(name="nota2")
    public Integer getNota2() {
        return this.nota2;
    }
    
    public void setNota2(Integer nota2) {
        this.nota2 = nota2;
    }

    
    @Column(name="nota3")
    public Integer getNota3() {
        return this.nota3;
    }
    
    public void setNota3(Integer nota3) {
        this.nota3 = nota3;
    }

    
    @Column(name="promedio", precision=22, scale=0)
    public Double getPromedio() {
        return this.promedio;
    }
    
    public void setPromedio(Double promedio) {
        this.promedio = promedio;
    }




}


